### ISSUE TITLE
Set MaxHealth on first server join?

### ISSUE THREAD

**Issue by AnnieReuvers** [P0ckey/SetMaxHealth#1]
Hey there, I was wondering if it was possible to set MaxHealth on a players first join. That way all players have extra health forever, regardless of them being online or not...

**Comment by le0lyu** [comment]
Working on it :) I’ll give you an update when it’s implemented

**Comment by le0lyu** [comment]
I’ve now made sure that works! Previously it was a feature but there was a bug, try now and feel free to contact me again if there’s any further issues! Now if you set the max health of a player make sure to lock them if you want their max health to stay when the login again, or else they’ll be reverted back to default health.
